ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0xfb3d951fa8496c6933ea0275695bca906c58527e"

[traps]

[traps.high_value_transfer_trap]
path = "out/HighValueTransferTrap.sol/HighValueTransferTrap.json"
address = "0x0000000000000000000000000000000000000000"
response_contract = "0x0000000000000000000000000000000000000000"
response_function = "handleHighValueTransfer(address,address,address,uint256,uint256)"
cooldown_period_blocks = 0
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 5
private_trap = true
whitelist = []
